START TRANSACTION;

CREATE TABLE "Users" (
                         "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                         "Name" character varying(100) NOT NULL,
                         CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250926102613_InitialCreate', '9.0.9');

COMMIT;
