START TRANSACTION;

CREATE TABLE "Users" (
                         "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                         "Name" character varying(100) NOT NULL,
                         CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


COMMIT;
